# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Linux配置 /home/yaan/uploadPath）
  profile: /home/yaan/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: char

amap:
  key: 7b0b64174ef6951cc6ee669de03e4f59

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
    basedir: logistics/tomcat

# 日志配置
logging:
  level:
    com.ruoyi: debug         # 自定义包的日志级别
    org.springframework: warn  # Spring Framework 的日志级别
    root: INFO               # 根日志级别

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  #Jackson 全局时间格式
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 47.92.216.173
#    host: 172.26.86.64
#     端口，默认为6379
    port: 7655
#    port: 6379
    # 数据库索引
    database: 0
    # 密码
#    password: yaangis@2024
    password: zhangsan
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#MQTT客户端
publish:
  mqtt:
#    host: tcp://49.233.206.13:1883
#    clientId: mqtt_publish
#    options:
#      userName: hitesh
#      password: zhangsan
    host: tcp://154.8.204.167:21883
    clientId: 9897b507fe0143d6a0d05517781bbc7f
    options:
      username: 8099H9XE
      password: 4OUWTTWN
      # 这里表示会话不过期
      cleanSession: false
      # 配置一个默认的主题，加载时不会用到，只能在需要时手动提取
      defaultTopic: devops
      timeout: 1000
      KeepAliveInterval: 10
      #断线重连方式，自动重新连接与会话不过期配合使用会导致
      #断线重新连接后会接收到断线期间的消息。需要更改设置请看password联系我
      automaticReconnect: true
      connectionTimeout: 3000
      # 最大链接数
      maxInflight: 100

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: auto
  type-handlers-package: com.ruoyi.system.domain.handler

# PageHelper分页插件
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 第三方接口配置
third-party:
  username: test
  passowrd: Open#Api2025!

